name: Blog Post

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@1.8.7
        with:
          feed_list: https://blog.invictusqiu.top/atom.xml
